openapi: 3.0.0
info:
  version: "0.1"
  title: ceklog backend
  description: "Ceklog, a digital solution for you to increase discipline in working hour, accurate location points and realtime attendance"
  contact:
    name: "Samsul Hadi"
    email: "samsulhadikediri@gmail.com"

servers:
  - url: https://{your-own-host}:{your-own-port}/{your-own-optional-prefix}
    description: Format URL
  - url: http://localhost:8000
    description: Local development

paths:

  /api/v1/account/login/:
    post:
      tags:
       - "Users"
      summary: Logs user into the system
      description: |
        Logging in a user with username and password and return user details.

        Example CURL:
        ```
        curl --location --request POST 'http://localhost:8000/api/v1/account/login/' \
        --header 'Content-Type: application/json' \
        --data-raw '{
            "username": "example@gmail.com",
            "password": "password"
        }'
        ```
      requestBody:
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                password:
                  type: string
                  format: password
      responses:
        200:
          description: >-
            Login success
          content:
            application/json:
              schema:
                properties:
                  refresh:
                    type: string
                    example: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ"
                  access:
                    type: string
                    example: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ"
        400:
          description: >-
            Invalid payload.
          content:
            application/json:
              schema:
                properties:
                  username:
                    type: string
                    example: "This field may not be null"
                  password:
                    type: string
                    example: "This field may not be blank"

        401:
          description: >-
            Invalid login.
          content:
            application/json:
              schema:
                properties:
                  detail:
                    type: string
                    example: "No active account found with the given credential"

  /api/v1/account/logout/:
    post:
      tags:
       - "Users"
      summary: Logs out current logged in user session
      description: |
        Example CURL:
        ```
        curl --location --request POST 'http://localhost:8000/api/v1/account/logout/' \
        --header 'Authorization: Bearer {{JWT_TOKEN}}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
            "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY0ODk2NzMyNCwiaWF0IjoxNjQ4ODgwOTI0LCJqdGkiOiI0NTg2ODZlNWQ3OTU0NzdkOTM4YWY2NTQwZGUxMzEyMCIsInVzZXJfaWQiOjF9.o_a6vLI14o7Fem9ozKNl9qolOcepn5aE70anrD_RJRY"
        }'
        ```
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                refresh_token:
                  type: string
                  format: password

      responses:
        400:
          description: >-
            Refresh token is not valid
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                    default: False
                  massage:
                    type: string
                    example: "Refresh Token not valid"
        200:
          description: >-
            Access Token Validate.
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                    default: True
                  massage:
                    type: string
                    example: "Logout successfully."

  /api/v1/account/token/refresh/:
    post:
      tags:
       - "Users"
      summary: Refresh the access token or get a new access token
      description: |
        Example CURL:
        ```
        curl --location --request POST 'http://localhost:8000/api/v1/account/token/refresh/' \
        --header 'Content-Type: application/json' \
        --data-raw '{
            "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY0ODk2NzMyNCwiaWF0IjoxNjQ4ODgwOTI0LCJqdGkiOiI0NTg2ODZlNWQ3OTU0NzdkOTM4YWY2NTQwZGUxMzEyMCIsInVzZXJfaWQiOjF9"
        }'
        ```

      requestBody:
        content:
          application/json:
            schema:
              properties:
                refresh_token:
                  type: string
                  format: password

      responses:
        400:
          description: >-
            Invalid payload.
          content:
            application/json:
              schema:
                properties:
                  refresh:
                    type: array
                    example: ["Token is invalid or expired"]
        401:
          description: >-
            Unauthorized. Refresh token is not valid
          content:
            application/json:
              schema:
                properties:
                  detail:
                    type: string
                    example: "Token is invalid or expired"
        200:
          description: >-
            Get new access token.
          content:
            application/json:
              schema:
                properties:
                  access:
                    type: string
                    example: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT